import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, LinearProgress, Typography } from "@mui/material";
import Appbar from "../componets/Appbar/Appbar";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Pomodoro Timer Online - Pomofocus</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Appbar />
        <div className={styles.main}>
          <div className={styles.centerBox}>
            <div className={styles.centerBoxItems}></div>
            <div className={styles.centerBoxItems}>
              <Button
                variant="contained"
                sx={{ bgcolor: "#fff", color: "rgb(217, 85, 80)" }}
              >
                Start
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.taskItem}>
        <Typography>list</Typography>
      </div>
    </>
  );
}
